// Generated by jextract

package fr.sciam.sqlite;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*fts5_extension_function)(const Fts5ExtensionApi *, Fts5Context *, sqlite3_context *, int, sqlite3_value **)
 * }
 */
public class fts5_extension_function {

    fts5_extension_function() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment pApi, MemorySegment pFts, MemorySegment pCtx, int nVal, MemorySegment apVal);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        SQLite3.C_POINTER,
        SQLite3.C_POINTER,
        SQLite3.C_POINTER,
        SQLite3.C_INT,
        SQLite3.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SQLite3.upcallHandle(fts5_extension_function.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(fts5_extension_function.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment pApi, MemorySegment pFts, MemorySegment pCtx, int nVal, MemorySegment apVal) {
        try {
             DOWN$MH.invokeExact(funcPtr, pApi, pFts, pCtx, nVal, apVal);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

